### ISSUE TITLE
Enable running the client under Windows 7 or 8.

### ISSUE THREAD

**Issue by eugeniomiro** [eugeniomiro/Terrarium#5]

**Comment by ptiza-v-nebe** [comment]
There a way how to enable Terrarium on Windows 7,8 and 10. 32 bit and 64 bit!
Problem is DirectDraw is deprecated so we need this three files to enable functions used in this old technology.
google for dx7vb.dll, dx8vb.dll, dxdrm.dll (there is plenty websites with this dlls)

then do this:

**x32 bit system**
1 in windows 7,8,10 copy dx7vb.dll, dx8vb.dll, dxdrm.dll to system32
2 run with administrative privileges "cmd"
3 execute this:
regsvr32 dx7vb
regsvr32 dx8vb


**x64 bit system**
1 in windows 7,8,10 copy dx7vb.dll, dx8vb.dll, dxdrm.dll to system32 and sysWOW64
2 run with administrative privileges "cmd"
3 regsvr32 %systemroot%\SysWOW64\dx7vb.dll
regsvr32 %systemroot%\SysWOW64\dx8vb.dll

**Comment by eugeniomiro** [comment]
Thanks for the suggestion @ptiza-v-nebe!!! I searched the internet and downloaded the first two of them I found but none of them were COM servers so they were not able to be registered with ```regsvr32``` command, will keep searching and let you know what I find.
in the meantime, if you have a URL that may take me to the good one please send me that. Thanks!

**Comment by eugeniomiro** [comment]
my email is eugenio.miro@gmail.com

**Comment by eugeniomiro** [comment]
you were right @ptiza-v-nebe!, I ran the regsvr32 command from an elevated command line and that worked like a charm! 
thanks!

**Comment by eugeniomiro** [comment]
Fixed with Terrarium 2.1.6116.26312!

**Comment by ptiza-v-nebe** [comment]
I did little research with dll export viewer. As it seems you need only dx7vb.dll.
If I unregister/delete dx8vb.dll and delete d3drm.dll the Terrarium Client is running anyway.
